TYPO3:
  Form:
    yamlPersistenceManager:
      savePath: 'resource://MapSeven.Bootstrap/Private/Form/'
    presets:
      bootstrap:
        title: 'Twitter bootstrap'
        parentPreset: 'default'
        formElementTypes:
          'TYPO3.Form:Form':
            renderingOptions:
              templatePathPattern: 'resource://MapSeven.Bootstrap/Private/Templates/Form/Form.html'
          'TYPO3.Form:Base':
            renderingOptions:
              layoutPathPattern: 'resource://MapSeven.Bootstrap/Private/Templates/Form/{@type}.html'
          'TYPO3.Form:Page':
            renderingOptions:
              templatePathPattern: 'resource://MapSeven.Bootstrap/Private/Templates/Form/Page.html'
          'TYPO3.Form:FormElement':
            properties:
              elementClassAttribute: 'form-control'
          'TYPO3.Form:MultiLineText':
            properties:
              elementClassAttribute: 'form-control'